name: C++ CI Pipeline (MSBuild & Native Unit Tests)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild "Unit Test\Unit Test.slnx" /p:Configuration=Release /p:Platform=x64

    - name: Run Native Unit Tests
      shell: cmd
      run: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" "Unit Test\x64\Release\Unit Test.dll"'